
class MotorMode(object):
    MOTOR_OFF = 0
    MOTOR_FWD = 1
    MOTOR_REV = 2
    MOTOR_BRK = 3
    MOTOR_IGNORE = 4


# STREAMING CONSTANTS
KEY_STRM_GYRO_Z = "GYRO_Z"

KEY_STRM_GYRO_Y = "GYRO_Y"

KEY_STRM_GYRO_X = "GYRO_X"

KEY_STRM_ACC_Z = "ACC_Z"

KEY_STRM_ACC_Y = "ACC_Y"

KEY_STRM_ACC_X = "ACC_X"

KEY_STRM_IMU_YAW_ANGLE = "IMU_YAW_ANGLE"

KEY_STRM_IMU_ROLL_ANGLE = "IMU_ROLL_ANGLE"

KEY_STRM_IMU_PITCH_ANGLE = "IMU_PITCH_ANGLE"

KEY_STRM_PWM_RAW_RIGHT_MOTOR = "PWM_RAW_RIGHT_MOTOR"

KEY_STRM_PWM_RAW_LEFT_MOTOR = "PWM_RAW_LEFT_MOTOR"

KEY_STRM_EMF_RAW_LEFT_MOTOR = "EMF_RAW_LEFT_MOTOR"

KEY_STRM_EMF_RAW_RIGHT_MOTOR = "EMF_RAW_RIGHT_MOTOR"

KEY_EMF_LEFT_MOTOR = "EMF_LEFT_MOTOR"

KEY_EMF_RIGHT_MOTOR = "EMF_RIGHT_MOTOR"

KEY_STRM_GYRO_Z_RAW = "GYRO_Z_RAW"

KEY_STRM_GYRO_Y_RAW = "GYRO_Y_RAW"

KEY_STRM_GYRO_X_RAW = "GYRO_X_RAW"

KEY_STRM_Z_RAW = "ACC_Z_RAW"

KEY_STRM_Y_RAW = "ACC_Y_RAW"

KEY_STRM_X_RAW = "ACC_X_RAW"

KEY_STRM_VELOCITY_Y = "VELOCITY_Y"

KEY_STRM_VELOCITY_X = "VELOCITY_X"

KEY_STRM_ACCEL_ONE = "ACCEL_ONE"

KEY_STRM_ODOMETER_Y = "ODOMETER_Y"

KEY_STRM_ODOMETER_X = "ODOMETER_X"

KEY_STRM_Q3 = "Q3"

KEY_STRM_Q2 = "Q2"

KEY_STRM_Q1 = "Q1"

KEY_STRM_Q0 = "Q0"
